export const arr = [
  "Public Service and Government",
  "Science, Technology, Engineering, and Math (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Education and Training",
  "Education and Training",
  "Arts, Media, and Communication",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Arts, Media, and Communication:",
  "Public Service and Government:",
  "Arts, Media, and Communication",
  "Business and Management",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Trades and Services",
  "Trades and Services",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Math (STEM)",
  "Education and Training",
  "Science, Technology, Engineering, and Mathematics",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Arts, Media, and Communication",
  "Education and Training",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Public Service and Government:",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Healthcare and Medicine:",
  "Business and Management",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Business and Management",
  "Business and Management:",
  "Business and Management:",
  "Public Service and Government",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Math (STEM)",
  "Healthcare and Medicine",
  "Education and Training",
  "Science, Technology, Engineering, and Mathematics",
  "Public Service and Government",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Trades and Services",
  "Public Service and Government",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics",
  "Business and Management:",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Math (STEM)",
  "Arts, Media, and Communication",
  "Business and Management:",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Education and Training",
  "Arts, Media, and Communication",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics",
  "Healthcare and Medicine",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Public Service and Government",
  "Education and Training",
  "Public Service and Government",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Public Service and Government:",
  "Science, Technology, Engineering, and Mathematics (STEM",
  "Healthcare and Medicine",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Business and Management",
  "Business and Management",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics",
  "Healthcare and Medicine",
  "Arts, Media, and Communication",
  "Public Service and Government",
  "Healthcare and Medicine",
  "Healthcare and Medicine",
  "Arts, Media, and Communication:",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Healthcare and Medicine",
  "Healthcare and Medicine",
  "Business and Management",
  "Business and Management",
  "Science, Technology, Engineering, and Mathematics",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Arts, Media, and Communication",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Business and Management",
  "Healthcare and Medicine:",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Arts, Media, and Communication",
  "Public Service and Government:",
  "Healthcare and Medicine:",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Trades and Services",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Business and Management:",
  "Arts, Media, and Communication",
  "Healthcare and Medicine",
  "Arts, Media, and Communication:",
  "Trades and Services",
  "Public Service and Government:",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Public Service and Government:",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Arts, Media, and Communication",
  "Education and Training",
  "Science, Technology, Engineering, and Math (STEM)",
  "Business and Management:",
  "Arts, Media, and Communication",
  "Business and Management",
  "Science, Technology, Engineering, and Math (STEM)",
  "Public Service and Government:",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Math (STEM)",
  "Business and Management",
  "Education and Training",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Public Service and Government:",
  "Healthcare and Medicine:",
  "Healthcare and Medicine",
  "Education and Training",
  "Education and Training",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Trades and Services",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Public Service and Government:",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Arts, Media, and Communication",
  "Arts, Media, and Communication",
  "Trades and Services",
  "Public Service and Government",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Math (STEM)",
  "Trades and Services",
  "Trades and Services",
  "Healthcare and Medicine:",
  "Public Service and Government:",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics",
  "Arts, Media, and Communication",
  "Business and Management:",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics",
  "Trades and Services",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics",
  "Trades and Services",
  "Arts, Media, and Communication",
  "Business and Management",
  "Arts, Media, and Communication",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Arts, Media, and Communication",
  "Arts, Media, and Communication",
  "Public Service and Government:",
  "Business and Management",
  "Public Service and Government",
  "Business and Management:",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Math (STEM)",
  "Healthcare and Medicine",
  "Public Service and Government:",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Healthcare and Medicine:",
  "Trades and Services",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Business and Management",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Trades and Services",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Healthcare and Medicine",
  "Trades and Services",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Public Service and Government:",
  "Trades and Services",
  "Healthcare and Medicine",
  "Trades and Services",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Business and Management:",
  "Public Service and Government:",
  "Business and Management",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Trades and Services",
  "Trades and Services",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Public Service and Government:",
  "Science, Technology, Engineering, and Math (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Trades and Services",
  "Education and Training",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Trades and Services",
  "Business and Management:",
  "Arts, Media, and Communication:",
  "Public Service and Government:",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Trades and Services",
  "Healthcare and Medicine",
  "Healthcare and Medicine",
  "Public Service and Government:",
  "Trades and Services",
  "Arts, Media, and Communication",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Trades and Services",
  "Public Service and Government",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Healthcare and Medicine:",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Healthcare and Medicine",
  "Trades and Services",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Trades and Services",
  "Business and Management",
  "Public Service and Government",
  "Arts, Media, and Communication",
  "Trades and Services",
  "Public Service and Government:",
  "Trades and Services",
  "Business and Management:",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Healthcare and Medicine",
  "Education and Training",
  "Trades and Services",
  "Arts, Media, and Communication",
  "Arts, Media, and Communication:",
  "Public Service and Government",
  "Healthcare and Medicine:",
  "Trades and Services",
  "Education and Training:",
  "Science, Technology, Engineering, and Math (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Business and Management:",
  "Business and Management",
  "Education and Training",
  "Business and Management",
  "Science, Technology, Engineering, and Mathematics",
  "Public Service and Government",
  "Science, Technology, Engineering, and Mathematics (STEM",
  "Arts, Media, and Communication",
  "Public Service and Government:",
  "Education and Training",
  "Arts, Media, and Communication",
  "Business and Management",
  "Science, Technology, Engineering, and Math (STEM)",
  "Public Service and Government",
  "Healthcare and Medicine:",
  "Public Service and Government:",
  "Healthcare and Medicine:",
  "Trades and Services",
  "Trades and Services",
  "Business and Management",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Trades and Services",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Public Service and Government",
  "Trades and Services",
  "Public Service and Government:",
  "Healthcare and Medicine:",
  "Arts, Media, and Communication",
  "Trades and Services",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Public Service and Government",
  "Business and Management",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Trades and Services",
  "Business and Management",
  "Healthcare and Medicine",
  "Education and Training",
  "Healthcare and Medicine:",
  "Science, Technology, Engineering, and Math (STEM)",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Trades and Services",
  "Science, Technology, Engineering, and Math (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Education and Training",
  "Science, Technology, Engineering, and Mathematics",
  "Healthcare and Medicine:",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Trades and Services",
  "Trades and Services",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics (STEM",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Arts, Media, and Communication",
  "Trades and Services",
  "Public Service and Government:",
  "Trades and Services",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Public Service and Government:",
  "Public Service and Government:",
  "Science, Technology, Engineering, and Mathematics (STEM",
  "Public Service and Government",
  "Arts, Media, and Communication",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics",
  "Science, Technology, Engineering, and Math (STEM)",
  "Trades and Services",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics (STEM",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Public Service and Government:",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Arts, Media, and Communication",
  "Trades and Services",
  "Education and Training",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Healthcare and Medicine:",
  "Business and Management:",
  "Arts, Media, and Communication",
  "Trades and Services",
  "Education and Training",
  "Business and Management",
  "Public Service and Government",
  "Healthcare and Medicine",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Math (STEM)",
  "Education and Training",
  "Public Service and Government:",
  "Science, Technology, Engineering, and Math (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Arts, Media, and Communication:",
  "Education and Training",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Business and Management:",
  "Healthcare and Medicine",
  "Public Service and Government:",
  "Arts, Media, and Communication:",
  "Arts, Media, and Communication",
  "Trades and Services",
  "Business and Management",
  "Education and Training",
  "Education and Training",
  "Education and Training",
  "Trades and Services",
  "Public Service and Government",
  "Science, Technology, Engineering, and Math (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Education and Training",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Trades and Services",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Healthcare and Medicine:",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Education and Training",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Education and Training",
  "Trades and Services",
  "Arts, Media, and Communication",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Public Service and Government:",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Trades and Services",
  "Arts, Media, and Communication",
  "Business and Management:",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Education and Training",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Math (STEM)",
  "Public Service and Government",
  "Business and Management",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics",
  "Trades and Services",
  "Trades and Services",
  "Business and Management",
  "Education and Training",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Trades and Services",
  "Arts, Media, and Communication:",
  "Education and Training",
  "Education and Training",
  "Education and Training",
  "Education and Training",
  "Business and Management",
  "Trades and Services",
  "Public Service and Government:",
  "Public Service and Government:",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Business and Management:",
  "Business and Management",
  "Business and Management",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Public Service and Government:",
  "Education and Training",
  "Trades and Services",
  "Public Service and Government",
  "transportation and material moving occupations.",
  "Business and Management",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Business and Management",
  "Education and Training",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Business and Management",
  "Trades and Services",
  "Trades and Services",
  "Trades and Services",
  "Education and Training",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Business and Management",
  "Science, Technology, Engineering, and Mathematics",
  "Business and Management:",
  "Public Service and Government",
  "Science, Technology, Engineering, and Mathematics",
  "Business and Management:",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Arts, Media, and Communication:",
  "Trades and Services",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics",
  "Business and Management",
  "Science, Technology, Engineering, and Math (STEM)",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Trades and Services",
  "Trades and Services",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Public Service and Government:",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Public Service and Government",
  "Trades and Services",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Education and Training:",
  "Business and Management:",
  "Education and Training",
  "Arts, Media, and Communication",
  "Arts, Media, and Communication",
  "Healthcare and Medicine:",
  "Trades and Services",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Public Service and Government:",
  "Trades and Services",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Trades and Services",
  "Education and Training",
  "Trades and Services",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Public Service and Government:",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Business and Management",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Education and Training",
  "Business and Management",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Trades and Services",
  "Public Service and Government:",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Public Service and Government",
  "Business and Management",
  "Public Service and Government:",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Public Service and Government",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Education and Training:",
  "Trades and Services",
  "Trades and Services",
  "Public Service and Government",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Education and Training",
  "Healthcare and Medicine:",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Trades and Services",
  "Arts, Media, and Communication:",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Business and Management:",
  "Public Service and Government:",
  "Public Service and Government:",
  "Public Service and Government:",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Business and Management:",
  "Business and Management:",
  "Public Service and Government",
  "Business and Management:",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Arts, Media, and Communication",
  "Healthcare and Medicine",
  "Business and Management:",
  "Healthcare and Medicine",
  "Healthcare and Medicine:",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Arts, Media, and Communication",
  "Education and Training",
  "Science, Technology, Engineering, and Math (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Education and Training",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Math (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Business and Management:",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Business and Management",
  "Public Service and Government:",
  "Education and Training",
  "Public Service and Government:",
  "Business and Management",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Education and Training",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Education and Training",
  "Education and Training",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Business and Management",
  "Business and Management",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Business and Management:",
  "Trades and Services",
  "Science, Technology, Engineering, and Math (STEM)",
  "Healthcare and Medicine",
  "Public Service and Government:",
  "Trades and Services",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics (STEM",
  "Science, Technology, Engineering, and Mathematics (STEM",
  "Public Service and Government",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Arts, Media, and Communication:",
  "Healthcare and Medicine",
  "Business and Management",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Trades and Services",
  "Business and Management:",
  "Public Service and Government",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Business and Management:",
  "Science, Technology, Engineering, and Mathematics",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Education and Training",
  "Trades and Services",
  "Science, Technology, Engineering, and Math (STEM)",
  "Healthcare and Medicine:",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Public Service and Government:",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Business and Management",
  "Healthcare and Medicine",
  "Arts, Media, and Communication:",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Business and Management:",
  "Trades and Services",
  "Arts, Media, and Communication",
  "Education and Training",
  "Science, Technology, Engineering, and Math (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Education and Training",
  "Science, Technology, Engineering, and Mathematics (STEM",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Business and Management:",
  "Business and Management:",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics",
  "Education and Training",
  "Public Service and Government",
  "Education and Training",
  "Education and Training",
  "Public Service and Government",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Trades and Services",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Education and Training",
  "Science, Technology, Engineering, and Mathematics",
  "Arts, Media, and Communication",
  "Trades and Services",
  "Education and Training",
  "Business and Management:",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Public Service and Government:",
  "Science, Technology, Engineering, and Math (STEM)",
  "Public Service and Government",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Healthcare and Medicine",
  "Trades and Services",
  "Business and Management:",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Business and Management",
  "Science, Technology, Engineering, and Mathematics",
  "Business and Management:",
  "Education and Training",
  "Trades and Services",
  "Healthcare and Medicine",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Arts, Media, and Communication:",
  "Healthcare and Medicine:",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Business and Management",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Trades and Services",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics (STEM",
  "Healthcare and Medicine",
  "Public Service and Government:",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM): Science, Technology, Engineering, and Mathematics (STEM):",
  "Education and Training",
  "Education and Training",
  "Trades and Services",
  "Trades and Services",
  "Healthcare and Medicine",
  "Public Service and Government:",
  "Business and Management",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Trades and Services",
  "Healthcare and Medicine:",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Trades and Services",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Trades and Services",
  "Business and Management",
  "Arts, Media, and Communication:",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Healthcare and Medicine",
  "Trades and Services",
  "Trades and Services",
  "Healthcare and Medicine",
  "Education and Training",
  "Science, Technology, Engineering, and Math (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Trades and Services",
  "Arts, Media, and Communication",
  "Education and Training",
  "Arts, Media, and Communication",
  "Business and Management",
  "Business and Management:",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Trades and Services",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Business and Management:",
  "Business and Management:",
  "Trades and Services",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Math (STEM)",
  "Arts, Media, and Communication:",
  "Trades and Services",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics",
  "Healthcare and Medicine",
  "Public Service and Government:",
  "Public Service and Government:",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Arts, Media, and Communication",
  "Trades and Services",
  "Public Service and Government:",
  "Science, Technology, Engineering, and Math (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Healthcare and Medicine",
  "Public Service and Government",
  "Business and Management",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics",
  "Trades and Services",
  "Business and Management:",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Healthcare and Medicine",
  "Education and Training",
  "Arts, Media, and Communication:",
  "Healthcare and Medicine:",
  "Science, Technology, Engineering, and Mathematics (STEM",
  "Trades and Services",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Public Service and Government:",
  "Trades and Services",
  "Business and Management:",
  "Healthcare and Medicine:",
  "Arts, Media, and Communication",
  "Education and Training",
  "Business and Management",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics",
  "Healthcare and Medicine",
  "Public Service and Government",
  "Trades and Services",
  "Business and Management:",
  "Trades and Services",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Public Service and Government:",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM",
  "Public Service and Government",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Public Service and Government",
  "Public Service and Government",
  "Trades and Services",
  "Business and Management",
  "Trades and Services",
  "Public Service and Government",
  "Science, Technology, Engineering, and Math (STEM)",
  "Public Service and Government",
  "Education and Training",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Arts, Media, and Communication",
  "Trades and Services",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Healthcare and Medicine:",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Healthcare and Medicine",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Public Service and Government:",
  "Science, Technology, Engineering, and Mathematics",
  "Arts, Media, and Communication",
  "Business and Management:",
  "Education and Training",
  "Trades and Services",
  "Public Service and Government",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Business and Management:",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Arts, Media, and Communication",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Education and Training",
  "Arts, Media, and Communication",
  "Education and Training",
  "Business and Management",
  "Business and Management:",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Trades and Services",
  "Business and Management:",
  "Public Service and Government:",
  "Trades and Services",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Business and Management:",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Public Service and Government",
  "Public Service and Government",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Public Service and Government",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Arts, Media, and Communication",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics (STEM",
  "Public Service and Government",
  "Education and Training",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Business and Management:",
  "Public Service and Government:",
  "Trades and Services",
  "Business and Management",
  "Business and Management:",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Healthcare and Medicine",
  "Healthcare and Medicine",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM",
  "Healthcare and Medicine:",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Trades and Services",
  "Healthcare and Medicine:",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Education and Training",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Math (STEM)",
  "Arts, Media, and Communication",
  "Business and Management",
  "Business and Management",
  "Business and Management:",
  "Arts, Media, and Communication",
  "construction and extraction occupations.",
  "Arts, Media, and Communication:",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics",
  "Arts, Media, and Communication:",
  "Trades and Services",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Trades and Services",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Business and Management",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Business and Management:",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Math (STEM)",
  "Healthcare and Medicine",
  "Trades and Services",
  "Healthcare and Medicine:",
  "Public Service and Government",
  "Science, Technology, Engineering, and Mathematics (STEM",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Public Service and Government",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Healthcare and Medicine",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM",
  "Trades and Services",
  "Education and Training",
  "Trades and Services",
  "Business and Management:",
  "Public Service and Government",
  "Arts, Media, and Communication",
  "Healthcare and Medicine",
  "Trades and Services",
  "Trades and Services",
  "Public Service and Government:",
  "Education and Training",
  "Business and Management:",
  "Arts, Media, and Communication",
  "Education and Training",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Trades and Services",
  "Trades and Services",
  "Public Service and Government:",
  "Business and Management:",
  "Trades and Services",
  "Business and Management",
  "Trades and Services",
  "community and social service occupations.",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Math (STEM)",
  "Science, Technology, Engineering, and Math (STEM)",
  "Healthcare and Medicine:",
  "Healthcare and Medicine",
  "Public Service and Government",
  "Science, Technology, Engineering, and Math (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Public Service and Government",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Education and Training",
  "Healthcare and Medicine:",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Math (STEM)",
  "Business and Management:",
  "Business and Management:",
  "Trades and Services",
  "Arts, Media, and Communication",
  "Trades and Services",
  "Education and Training",
  "Education and Training",
  "Public Service and Government:",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Arts, Media, and Communication:",
  "Trades and Services",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Trades and Services",
  "Healthcare and Medicine",
  "Business and Management",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Education and Training",
  "Business and Management",
  "Healthcare and Medicine:",
  "Healthcare and Medicine:",
  "Business and Management",
  "Healthcare and Medicine",
  "Trades and Services",
  "Education and Training",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Trades and Services",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Arts, Media, and Communication",
  "Business and Management:",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Business and Management:",
  "Public Service and Government:",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Business and Management:",
  "Arts, Media, and Communication",
  "Arts, Media, and Communication:",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Trades and Services",
  "Trades and Services",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Trades and Services",
  "Business and Management",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Trades and Services",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics",
  "Business and Management:",
  "Trades and Services",
  "Education and Training",
  "Healthcare and Medicine:",
  "Arts, Media, and Communication:",
  "Science, Technology, Engineering, and Mathematics",
  "Public Service and Government",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Public Service and Government:",
  "Business and Management",
  "Trades and Services",
  "Education and Training",
  "Business and Management",
  "Trades and Services",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Arts, Media, and Communication",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Public Service and Government",
  "Arts, Media, and Communication",
  "Education and Training",
  "Business and Management",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Trades and Services",
  "Education and Training",
  "Business and Management:",
  "Public Service and Government",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Public Service and Government:",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Healthcare and Medicine:",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Arts, Media, and Communication",
  "Business and Management",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Business and Management",
  "Healthcare and Medicine:",
  "Education and Training",
  "Business and Management",
  "Public Service and Government:",
  "Public Service and Government",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Business and Management:",
  "Trades and Services",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Math (STEM)",
  "Healthcare and Medicine",
  "Arts, Media, and Communication:",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Arts, Media, and Communication",
  "Healthcare and Medicine",
  "Public Service and Government",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Education and Training",
  "Trades and Services",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Public Service and Government",
  "Business and Management:",
  "Business and Management:",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics",
  "Education and Training",
  "Public Service and Government:",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Trades and Services",
  "Public Service and Government",
  "Healthcare and Medicine:",
  "Arts, Media, and Communication",
  "Trades and Services",
  "Arts, Media, and Communication:",
  "Public Service and Government",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics",
  "Science, Technology, Engineering, and Mathematics (STEM",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics",
  "Arts, Media, and Communication",
  "Healthcare and Medicine:",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Public Service and Government",
  "Public Service and Government",
  "Public Service and Government",
  "Trades and Services",
  "Trades and Services",
  "Trades and Services",
  "Healthcare and Medicine",
  "Public Service and Government:",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Business and Management",
  "Public Service and Government",
  "Public Service and Government",
  "Business and Management",
  "Science, Technology, Engineering, and Math (STEM)",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Healthcare and Medicine",
  "Public Service and Government",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Business and Management",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Arts, Media, and Communication:",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Public Service and Government",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics",
  "Science, Technology, Engineering, and Math (STEM)",
  "Arts, Media, and Communication:",
  "Arts, Media, and Communication",
  "Trades and Services",
  "Public Service and Government:",
  "Arts, Media, and Communication",
  "Education and Training",
  "Arts, Media, and Communication",
  "Trades and Services",
  "Public Service and Government",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Public Service and Government",
  "Public Service and Government:",
  "Education and Training",
  "Public Service and Government",
  "Public Service and Government",
  "Science, Technology, Engineering, and Mathematics",
  "Public Service and Government:",
  "Healthcare and Medicine:",
  "Science, Technology, Engineering, and Math (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Public Service and Government:",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Education and Training",
  "Healthcare and Medicine",
  "Trades and Services",
  "Business and Management",
  "Trades and Services",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Public Service and Government",
  "Arts, Media, and Communication",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Education and Training",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Education and Training",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Arts, Media, and Communication:",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Healthcare and Medicine",
  "Business and Management",
  "Trades and Services",
  "Healthcare and Medicine",
  "Business and Management:",
  "Business and Management:",
  "Science, Technology, Engineering, and Math (STEM)",
  "Education and Training",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Math (STEM)",
  "Science, Technology, Engineering, and Math (STEM)",
  "Arts, Media, and Communication",
  "Business and Management",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Math (STEM)",
  "Arts, Media, and Communication",
  "Trades and Services",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Math (STEM)",
  "Education and Training",
  "Public Service and Government:",
  "Public Service and Government",
  "Business and Management:",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Public Service and Government",
  "Healthcare and Medicine",
  "Trades and Services",
  "Healthcare and Medicine",
  "Healthcare and Medicine",
  "Business and Management",
  "Trades and Services",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Business and Management",
  "Public Service and Government",
  "Healthcare and Medicine",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics",
  "Education and Training",
  "Education and Training",
  "Healthcare and Medicine",
  "Trades and Services",
  "Healthcare and Medicine",
  "Science, Technology, Engineering, and Math (STEM)",
  "Business and Management:",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Healthcare and Medicine",
  "Trades and Services",
  "Healthcare and Medicine:",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Education and Training",
  "Trades and Services",
  "Public Service and Government:",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Healthcare and Medicine",
  "Trades and Services",
  "Public Service and Government",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Public Service and Government:",
  "Arts, Media, and Communication",
  "Arts, Media, and Communication",
  "Trades and Services",
  "Education and Training",
  "Arts, Media, and Communication:",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Business and Management:",
  "Science, Technology, Engineering, and Mathematics",
  "Education and Training",
  "Healthcare and Medicine:",
  "Education and Training",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Public Service and Government",
  "Healthcare and Medicine:",
  "Healthcare and Medicine:",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Public Service and Government",
  "Healthcare and Medicine",
  "Public Service and Government",
  "Science, Technology, Engineering, and Mathematics (STEM",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Trades and Services",
  "Trades and Services",
  "Trades and Services",
  "Public Service and Government:",
  "Science, Technology, Engineering, and Mathematics (STEM",
  "Business and Management:",
  "Education and Training",
  "Education and Training",
  "Business and Management",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Math (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Math (STEM)",
  "Business and Management",
  "Public Service and Government:",
  "Public Service and Government:",
  "Trades and Services",
  "Public Service and Government",
  "Science, Technology, Engineering, and Mathematics (STEM):",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Healthcare and Medicine",
  "Trades and Services",
  "Science, Technology, Engineering, and Mathematics",
  "Healthcare and Medicine:",
  "Business and Management",
  "Arts, Media, and Communication",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Science, Technology, Engineering, and Math (STEM)",
  "Business and Management:",
  "Public Service and Government:",
  "Science, Technology, Engineering, and Math (STEM)",
  "Trades and Services",
  "Education and Training",
  "Science, Technology, Engineering, and Mathematics (STEM)",
  "Education and Training",
  "Science, Technology, Engineering, and Mathematics (STEM)",
];


export const newArr = new Set(arr);
